services:
  network-deploy-service:
    networks:
      - tom

  db-config:
    extends:
      service: network-deploy-service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tom
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  app-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
