spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: info